### ISSUE TITLE
No escaping of special characters in attribute values of HTML tags

### ISSUE THREAD

**Issue by malin-as** [hanami/helpers#108]
Hi,

If I use the `div` helper like this in my Slim template:
```
= div 'data-story': 'My "own" story'
```
The resulting HTML is:
```html
<div data-story="My "own" story">
```
I can also reproduce that in IRB. I expected that the strings would automatically be escaped. Did I miss something? I think that having to do it by myself would defeat the point of using a helper in the first place.

**Comment by glaszig** [comment]
you should use the `ha` helper:

    = div 'data-story': ha('My "own" story')

there's more about escaping markup [in the docs](http://hanamirb.org/guides/1.0/helpers/escape/#escape-html-attributes).

**Comment by malin-as** [comment]
Thanks for the docs, I had missed that page.

However, it states (in bold text) that "This should be used only when the value of an attribute comes from a user input." I disagree about that. I could have automatically-generated values that come from some arbitrary library with no direct relationship to user data, and yet these values could need some escaping. It wouldn't necessarily be a security issue, but still be an issue.

I feel like I need defensive programming on my side where I'm going to `ha` everything, to have future-proof code. I think it would be much simpler if the `HtmlHelpers` were to escape the attributes by default, and provide a mechanism for producing raw values when the developer has a good reason for doing so.

**Comment by glaszig** [comment]
i agree, actually. just wanted to point out how they suggest you do it.

the approach should simply be reversed and escaping skipped if you do

    = div 'data-story': raw('My "own" story')

afaik, `#raw` returns an `Hanami::Utils::Escape::SafeString` which escapes escaping ;)

**Comment by jodosha** [comment]
Hi @malin-as your point is good, but we can't change this behavior as it is because of SemVer. I marked for future consideration, when we'll plan 2.0. Thanks.
