### ISSUE TITLE
Select and textarea helpers don't compute the correct name attribute

### ISSUE THREAD

**Issue by TiteiKo** [hanami/helpers#111]
Looking at [this](https://github.com/hanami/helpers/issues/110#issue-256972284) and [this](https://github.com/hanami/helpers/pull/107#issuecomment-326688700):

When inside a `fields_for_collection` block, indexes aren't stripped from `select` and `textearea` name attributes.

**Comment by davydovanton** [comment]
I think I can try to fix it 👍

**Comment by AlfonsoUceda** [comment]
@TiteiKo checking https://github.com/hanami/helpers/issues/110#issue-256972284 should we include hidden field to this issue?
