### ISSUE TITLE
Params break when `check_box` is used within `fields_for_collection`

### ISSUE THREAD

**Issue by nerdinand** [hanami/helpers#117]
When using `check_box` within a `fields_for_collection` block, the params hash can get screwed up. Here's a minimal example:
```ruby
<%=
  sub_entity1 = OpenStruct.new(key: false, id: 1)
  sub_entity2 = OpenStruct.new(key: false, id: 2)

  thing = OpenStruct.new(sub_entities: [sub_entity1, sub_entity2])

  form_for :thing, '/books/1', method: :put, values: {thing: thing} do
    fields_for_collection :sub_entities do
      hidden_field :id
      check_box :key, name: _displayed_input_name(:key) # workaround due to https://github.com/hanami/helpers/issues/116
    end
    submit 'Save'
  end
%>
```

When submitting the form with both checkboxes unchecked, the request data looks like this:
```
Name: Value
_method: PUT
thing[sub_entities][][id]: 1
thing[sub_entities][][key]: 0
thing[sub_entities][][id]: 2
thing[sub_entities][][key]: 0
```

Which results in the following params on the server:
```ruby
{
    :_method => "PUT",
      :thing => {
        :sub_entities => [
            {
                 "id" => "1",
                "key" => "0"
            },
            {
                 "id" => "2",
                "key" => "0"
            }
        ]
    },
         :id => "1"
}
```

That looks fine.

However, if you check one of the checkboxes and submit, the request data looks like this:

```
Name: Value
_method: PUT
thing[sub_entities][][id]: 1
thing[sub_entities][][key]: 0
thing[sub_entities][][key]: 1
thing[sub_entities][][id]: 2
thing[sub_entities][][key]: 0
```

Note the double `thing[sub_entities][][key]` because of the hidden field generated by `check_box`. Thus, after being parsed by Rack, the params hash is screwed up:

```ruby
{
    :_method => "PUT",
      :thing => {
        :sub_entities => [
            {
                 "id" => "1",
                "key" => "0"
            },
            {
                "key" => "1",
                 "id" => "2"
            },
            {
                "key" => "0"
            }
        ]
    },
         :id => "1"
}
```

Expected resulting params hash would be:

```ruby
{
    :_method => "PUT",
      :thing => {
        :sub_entities => [
            {
                 "id" => "1",
                "key" => "1"
            },
            {
                 "id" => "2",
                "key" => "0"
            }
        ]
    },
         :id => "1"
}
```

**Comment by nerdinand** [comment]
A possible workaround is something like:
```ruby
check_box :key, name: "#{_displayed_input_name(:key)}[][key]", value: 'true', id: nil # workaround due to https://github.com/hanami/helpers/issues/116 and https://github.com/hanami/helpers/issues/117
```

Of course, you then have to do some more work in the controller to work with those params...

**Comment by nerdinand** [comment]
BTW, I recently abandoned the idea to work with forms in hanami without JS, as it just wasn't practical for the rather complex forms I was building. Here's what I did instead:

View:
```haml
- hidden_field :quality_acceptable, class: 'radio-value-hidden'
- radio_button '', true, class: 'dont-submit'
- radio_button '', false, class: 'dont-submit
- radio_button '', nil, class: 'dont-submit'

= javascript 'radio-buttons.js'
= javascript 'form-dont-submit.js'
```

`radio-button.js`
```javascript
$(function() {
  $('.radio-value-hidden').each( function(index) {
    var hiddenInput = $(this);
    var initialValue = hiddenInput.val();
    var radioButtons = hiddenInput.parent().find('input[type=radio]')
    radioButtons.filter("[value='" + initialValue + "']").attr('checked', 'checked');

    radioButtons.attr("name", "radio-buttons-" + index);
    radioButtons.on("click", function(){
      selectedValue = $(this).val();
      hiddenInput.val(selectedValue);
    });
  });
});
```

`form-dont-submit.js`
```javascript
$('form').submit(function() {
   $(this).find('.dont-submit').remove();
});
```

**Comment by nerdinand** [comment]
And I have similar JS code for checkboxes too...

**Comment by AlfonsoUceda** [comment]
@nerdinand is radio button broken when using `fields_for_collection` too? Thanks for alerting us and sorry to hear that but we are working to improve it.

We have decided to remove hidden field when using checkboxes because it breaks how Rack parse nested fields.
```ruby
require 'rack'

def p(params)
  Rack::Utils.parse_nested_query(params)
end

p("p[checkbox]=0&p[checkox]=1")
# => {"p"=>{"checkbox"=>"1"}}

# Using your example
p("thing[sub_entities][][id]=1&thing[sub_entities][][key]=0&thing[sub_entities][][key]=1&thing[sub_entities][][id]=2&thing[sub_entities][][key]=0")
# => {"thing"=>{"sub_entities"=>[{"id"=>"1", "key"=>"0"}, {"key"=>"1", "id"=>"2"}, {"key"=>"0"}]}}
```

**Comment by nerdinand** [comment]
@AlfonsoUceda yes, that was exactly my problem... How does Rails solve this? I assume they have some unobtrusive JS magic similar to mine that takes care of the shortcomings of HTML forms?  Once again I'm baffled at how terribly designed HTML is... 

Maybe you should consider adding something like these JS helpers to Hanami?

**Comment by AlfonsoUceda** [comment]
@nerdinand I'm wondering how a radio button can be problematic in this context since if you have several radio button in the block, the selected radio will be sent, isn't it? I have to try it anyway.

**Comment by nerdinand** [comment]
Right, I don't quite remember what my problem with the radio buttons was. I think it was a combination of all the bugs I faced that made it make sense and seem easier to implement the same JS behaviour for check boxes and radio buttons...

**Comment by jodosha** [comment]
Closing as stale.
