### ISSUE TITLE
Cannot interleave Slim and Form Helpers

### ISSUE THREAD

**Issue by malin-as** [hanami/helpers#126]
Hi,

It is currently impossible to mix Slim and Form Helpers in a natural way. For instance, an abridged version of the following [bootstrap form](https://getbootstrap.com/docs/4.0/components/forms/#horizontal-form) does not render correctly if represented in this way:

```slim
= form_for 'test', '/' do
  .form-group.row
    label.col-sm-2.col-form-label
    .col-sm-10
      = email_field :email, class: 'form-control', placeholder: 'Email'
  fieldset.form-group
    .row
      legend.col-form-legend.col-sm-2 Radios
      .col-sm-10
        .form-check
          label.form-check-label
            = radio_button :gridradio, 'option1'
            | Option one is this and that—be sure to include why it's great
        .form-check
          label.form-check-label
            = radio_button :gridradio, 'option2'
            | Option two can be something else and selecting it will deselect option one
```
At the moment, the only way to solve this is to either create every node from the Html Helpers, or to create the form manually.

**Comment by AlfonsoUceda** [comment]
Thanks @malin-as can you provide the wrong output? Just for the record

**Comment by malin-as** [comment]
This is the output:

```html
<form action="/" method="POST" accept-charset="utf-8" id="test-form">
<input type="hidden" name="_csrf_token" value="eb7d7735…">
<input type="email" name="test[email]" id="test-email" value="" class="form-control" placeholder="Email">
<input type="radio" name="test[gridradio]" value="option1">
<input type="radio" name="test[gridradio]" value="option2">
```

**Comment by AlfonsoUceda** [comment]
@malin-as thanks! I'll try to research how to mix slim and form helpers

**Comment by davydovanton** [comment]
Some terrible expertise: I used `html` helper in view for render complicated forms. You can create different method in view object and use `super + html_method` for concatenate it 😞

**Comment by jodosha** [comment]
@malin-as Hi, I'm sorry about the poor experience, but this isn't a bug, it's a known limitation.

In order to design only one form helper for all the template engines, we had to introduce the compromise of one syntax block per from.

That means with ERB, you **can't** do this:

```erb
<%= form_for ... do %>
  <div>
    <%= submit "Send" %>
  <div>
<% end %>
```

Now that being said, I agree that it should be radically changed towards the syntax you tried to use, but this isn't a bug.
