### ISSUE TITLE
form_for with only a form object raises an error

### ISSUE THREAD

**Issue by pointlessone** [hanami/helpers#134]
[Example in docs](https://github.com/hanami/helpers/blob/fdce06d5123a427b21c37e55f5a6a3fd9943b7d9/lib/hanami/helpers/form_helper.rb#L150-L181) shows how `form_for` can be called with a form object.

However, [method signature](https://github.com/hanami/helpers/blob/master/lib/hanami/helpers/form_helper.rb#L409) looks like this:

```ruby
def form_for(name, url, options = {}, &blk)
```

Note that it has two mandatory positional arguments. This makes it impossible to call the method with only a form object (i.e. without options).

Here's the exception when `form_for` is called only with a form object (`form_for form_object do`):

```
ArgumentError: wrong number of arguments (given 1, expected 2..3)

[...]/hanami-helpers-1.1.1/lib/hanami/helpers/form_helper.rb:409:in `form_for'
```

**Comment by jodosha** [comment]
@pointlessone Hi and thanks for reporting.

Which version of `hanami` and `hanami-helpers` are you using? Can you please add a snippet of code here to reproduce the problem? TYVM!

**Comment by pointlessone** [comment]
## Gems

* `hanami`: 1.1.1
*  `hanami-helpers`: 1.1.1

## Example

View:

```ruby
module Admin::Views::Posts
  class Edit
    include Admin::View

    def post_form
      Form.new(
        :post,
        routes.post_path(id: post.id),
        {post: post},
        method: :patch
      )
    end
  end
end
```

Template (Slim):

```slim
= form_for post_form, {} do
  // rest of the form
```

Note the empty hash. According to docs it's optional.

**Comment by jodosha** [comment]
@pointlessone Thanks for your quick reply. Would you mind to manually test this fix?https://github.com/hanami/helpers/pull/135

To do so, edit your `Gemfile` like this:

```ruby
gem "hanami-helpers", git: "https://github.com/hanami/helpers.git", branch: "fix/form_for-signature-with-form-object"
```

Please put it **before** `gem "hanami"` declaration.
