### ISSUE TITLE
`label` helper doesn't accept block syntax

### ISSUE THREAD

**Issue by unleashy** [hanami/helpers#144]
Similar to #127, but with `label`. I'll make a PR as soon as I can.

Example use case:

```ruby
label for: :pizza do
  text 'Pizza '
  abbr '*', title: 'required', 'aria-label': 'required'
end
```

Which is more accessible than just having `label 'Pizza *', for: :pizza` :slightly_smiling_face: :pizza:

**Comment by unleashy** [comment]
Thanks, @arr-dev and @jodosha!

**Comment by jodosha** [comment]
@unleashy We'll release this one on next Fri.
