### ISSUE TITLE
Link_to helper for delete request

### ISSUE THREAD

**Issue by davydovanton** [hanami/helpers#49]
I think that it'll be really cool to create helper for `delete` request. For example `link_to_delete` Method which generate form with `delete` request. What do you think it'll be helpful?

**Comment by joneslee85** [comment]
I am not a very big fan of that counterpart feature in Rails. Because it generates form tags that might break the styling unexpectedly.

These days I want to do things obtrusively with integration test to back me up.

cc @AlfonsoUceda / @jodosha

**Comment by jodosha** [comment]
There is a way to avoid form tags, it's to use JavaScript to send a DELETE request. But we lack of this component and without it this feature request is incomplete.

To clarify, we can consider this in the future, but I'm not keen right now to implement JS features to pair with this special link.

**Comment by davydovanton** [comment]
I understood. Thanks!
