### ISSUE TITLE
Country select helper

### ISSUE THREAD

**Issue by cllns** [hanami/helpers#59]
[`country_select`](https://github.com/stefanpenner/country_select) is a useful Rails gem to generate a `select` of countries, with their country codes as values. I'm working on a `hanami` app right now that could benefit from it.

Can this be ported to Hanami? Note: Rails removed it from the `rails` project for political reasons: the names/existence of countries can be controversial. Hanami may wish to avoid that too, though going with ISO-3166 seems like a relatively fair option.

I'm happy to either build it into `hanami/helpers` or make my own gem for it.

**Comment by jodosha** [comment]
@cllns This is a good idea. :+1: 

What we aim for, is to NOT create a walled garden for Hanami Community, but something that all the Ruby ecosystem can benefit from.

For instance, all the `select` helpers across Hanami, Rails and Padrino accept an enumerable (Hash, or nested arrays). It would be nice if the first goal of your gem is to provide that basic data structure. Eg:

```ruby
module Countries
  def self.mapping
    { "it" => "Italy" }
  end
end
```

This is just Ruby, so all the Ruby projects can use this data structure to build their country select.

---

On the other hand, you can offer out-of-the-box support for Hanami. Eg.

```ruby
begin
  require 'hanami/helpers'
rescue LoadError
end

if defined?(Hanami::Helpers)
  # ...
end
```

WDYT?
