### ISSUE TITLE
Number formatting precision

### ISSUE THREAD

**Issue by TiteiKo** [hanami/helpers#77]
Hi all,

It looks like `NumberFormattingHelper` does not fully take into account the given precision:

``` ruby
format_number 3.14, precision: 0
# => 3.0 (instead of 3)
format_number 3.14, precision: 4
# => 3.14 (instead of 3.1400)
```

Is this by design?

**Comment by katafrakt** [comment]
Current implementation is based on Ruby `round` method, which behaves like that. See: https://ruby-doc.org/core-2.3.0/Float.html#method-i-round

This is quite correct when you realize that `format_number` returns a number, not a string. And of course:

```
irb(main):001:0> 3.14 == 3.14000
=> true
```

**Comment by cllns** [comment]
`format_number` [returns a String](https://github.com/hanami/helpers/blob/83e503078657aaec13d718534311be7074b2d509/lib/hanami/helpers/number_formatting_helper.rb#L31), not a number.

Maybe we should change the implementation to something like: 
```
sprintf('%.4f', "3.14") #=> "3.1400"
```
?

**Comment by TiteiKo** [comment]
@cllns Yep. One detail left: in case of an integer, user friendly use would be to have a default precision to 0, to avoid having `format_number(1000) == "1,000.00"` instead of `"1,000"`
