### ISSUE TITLE
Unable to insert 2 html5 methods in to form_for block

### ISSUE THREAD

**Issue by brbrr** [hanami/helpers#78]
Im trying to add 2 bootstrap radio buttons which is require nesting in `label` tag:

```
<div class="radio">
  <label><input type="radio" name="optradio">Option 1</label>
</div>
```

Its possible to do only with html helper (or with raw html insert in to form_for, which looks like not possible also). So I create method in view like so:

```
def radio_btn(radio_name, text_value)
      html.div(class: 'form-group') do
        div(class: 'radio') do
          label do
            input(name: radio_name, type: 'radio', value: radio_name)
            text(text_value)
          end
        end
      end
    end
```

and trying to render this template:

```
<%= form_for :message, routes.root_path do
  radio_btn('name1', 'Some text 1')
  radio_btn('name2', 'Some text 2')
end %>
```

but generated html include only last method call:

```
<body>
    <div class="container">
      <form action="/" method="POST" accept-charset="utf-8" id="message-form">
<div class="form-group">
<div class="radio">
<label><input name="name2" type="radio" value="name2">Some text 2</label>
</div>
</div>
</form>
</div>
</body>
```

The problem remains when I use more simple methods like

```
def test_1
      html.label 'test_1'
end
```

Im using latest hanami gem from ruby gems.

**Comment by mereghost** [comment]
It seems like a problem of context for the bindings used in Tilt (and Erubis). Try changing your methods to look like this: 

```ruby
def radio_btn(context, radio_name, text_value)
  context.div(class: 'form-group') do
    div(class: 'radio') do
      label do
        input(name: radio_name, type: 'radio', value: radio_name)
        text(text_value)
      end
    end
  end
end
```
And it's invocation to: `radio_btn(self, 'name1', 'Some text 1')` and see if that fix this for you.

**Comment by jodosha** [comment]
@brbrr Does @mereghost suggestion solves your problem?

**Comment by brbrr** [comment]
Yes, that helps. sorry for delay!

**Comment by jodosha** [comment]
@brbrr No worries. I'm glad you've fixed your issue.
@mereghost Thanks for helping @brbrr !
