### ISSUE TITLE
FormBuilder not filling the input fields

### ISSUE THREAD

**Issue by mereghost** [hanami/helpers#84]
Given a form with passed values: 

```ruby
<%= form_for :entity, routes.entities_path, values: { entity: Entity.new(field: 1) }
text_field :field
end %>
```

The text_field will not be filled at all. I tracked the problem down to the `Values#_get_from_values` [message](https://github.com/hanami/helpers/blob/master/lib/hanami/helpers/form_helper/values.rb#L44).

Now that entities are implicitly serializable to hashes (as they respond to `to_hash`), they become hashes during the `Values#initialize` and therefore the `public_send(k)` will always return `nil`.

**Comment by myabc** [comment]
Reproduced this error. Most likely a regression caused by https://github.com/hanami/utils/commit/6243607729b32e5d584ddcdfe07da3b4b5bc3271

**Comment by mereghost** [comment]
@dikond a fix that contemplates your use case was proposed on #87

**Comment by dikond** [comment]
Apparently, it doesn't. When the form initialized, it calls `.symbolize!` on the values, which recursively calls itself on the values which respond to `.to_hash`: 
https://github.com/hanami/utils/blob/master/lib/hanami/utils/hash.rb#L68

While this behaviour may be handy, it produces unexpected results when we have presenter object which responds to `to_hash` in the `values` options.
